-- MySQL Script generated by MySQL Workbench
-- 04/14/16 14:39:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KoersWest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KoersWest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KoersWest` DEFAULT CHARACTER SET utf8 ;
USE `KoersWest` ;

-- -----------------------------------------------------
-- Table `KoersWest`.`Gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Gebruiker` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `Wachtwoord` VARCHAR(45) NOT NULL,
  `telefoonnummer` VARCHAR(45) NOT NULL,
  `straat` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `woonplaats` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `KoersWest`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Categorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`Dienst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Dienst` (
  `id` INT NOT NULL,
  `dienst` VARCHAR(45) NOT NULL,
  `omschijving` TEXT(200) NOT NULL,
  `Afbeelding` BLOB NULL,
  `Catogorie_catogorie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dienst_Catogorie1_idx` (`Catogorie_catogorie_id` ASC),
  CONSTRAINT `fk_Dienst_Catogorie1`
    FOREIGN KEY (`Catogorie_catogorie_id`)
    REFERENCES `KoersWest`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`Gebruiker_bied_dienst_aan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Gebruiker_bied_dienst_aan` (
  `Gebruiker_Id` INT NOT NULL,
  `Dienst_id` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_Id`, `Dienst_id`),
  INDEX `fk_Gebruiker_has_Dienst_Dienst1_idx` (`Dienst_id` ASC),
  INDEX `fk_Gebruiker_has_Dienst_Gebruiker1_idx` (`Gebruiker_Id` ASC),
  CONSTRAINT `fk_Gebruiker_has_Dienst_Gebruiker1`
    FOREIGN KEY (`Gebruiker_Id`)
    REFERENCES `KoersWest`.`Gebruiker` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebruiker_has_Dienst_Dienst1`
    FOREIGN KEY (`Dienst_id`)
    REFERENCES `KoersWest`.`Dienst` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`Gebruiker_bied_dienst_aan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Gebruiker_bied_dienst_aan` (
  `Gebruiker_Id` INT NOT NULL,
  `Dienst_id` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_Id`, `Dienst_id`),
  INDEX `fk_Gebruiker_has_Dienst_Dienst1_idx` (`Dienst_id` ASC),
  INDEX `fk_Gebruiker_has_Dienst_Gebruiker1_idx` (`Gebruiker_Id` ASC),
  CONSTRAINT `fk_Gebruiker_has_Dienst_Gebruiker1`
    FOREIGN KEY (`Gebruiker_Id`)
    REFERENCES `KoersWest`.`Gebruiker` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebruiker_has_Dienst_Dienst1`
    FOREIGN KEY (`Dienst_id`)
    REFERENCES `KoersWest`.`Dienst` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`Gebruiker_vraagt_dienst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Gebruiker_vraagt_dienst` (
  `Gebruiker_Id` INT NOT NULL,
  `Dienst_id` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_Id`, `Dienst_id`),
  INDEX `fk_Gebruiker_has_Dienst_Dienst2_idx` (`Dienst_id` ASC),
  INDEX `fk_Gebruiker_has_Dienst_Gebruiker2_idx` (`Gebruiker_Id` ASC),
  CONSTRAINT `fk_Gebruiker_has_Dienst_Gebruiker2`
    FOREIGN KEY (`Gebruiker_Id`)
    REFERENCES `KoersWest`.`Gebruiker` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebruiker_has_Dienst_Dienst2`
    FOREIGN KEY (`Dienst_id`)
    REFERENCES `KoersWest`.`Dienst` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`Gebruiker_is_goed_in_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`Gebruiker_is_goed_in_categorie` (
  `Gebruiker_Id` INT NOT NULL,
  `Categorie_id` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_Id`, `Categorie_id`),
  INDEX `fk_Gebruiker_has_Catogorie_Catogorie1_idx` (`Categorie_id` ASC),
  INDEX `fk_Gebruiker_has_Catogorie_Gebruiker1_idx` (`Gebruiker_Id` ASC),
  CONSTRAINT `fk_Gebruiker_has_Catogorie_Gebruiker1`
    FOREIGN KEY (`Gebruiker_Id`)
    REFERENCES `KoersWest`.`Gebruiker` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebruiker_has_Catogorie_Catogorie1`
    FOREIGN KEY (`Categorie_id`)
    REFERENCES `KoersWest`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoersWest`.`gebruiker_is_slecht_in_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KoersWest`.`gebruiker_is_slecht_in_categorie` (
  `Gebruiker_Id` INT NOT NULL,
  `Categorie_id` INT NOT NULL,
  PRIMARY KEY (`Gebruiker_Id`, `Categorie_id`),
  INDEX `fk_Gebruiker_has_Catogorie1_Catogorie1_idx` (`Categorie_id` ASC),
  INDEX `fk_Gebruiker_has_Catogorie1_Gebruiker1_idx` (`Gebruiker_Id` ASC),
  CONSTRAINT `fk_Gebruiker_has_Catogorie1_Gebruiker1`
    FOREIGN KEY (`Gebruiker_Id`)
    REFERENCES `KoersWest`.`Gebruiker` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gebruiker_has_Catogorie1_Catogorie1`
    FOREIGN KEY (`Categorie_id`)
    REFERENCES `KoersWest`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
